### PR TITLE
add columns (ratio, uploaded)

### PR DESCRIPTION
**Pull request by Biorn1950**
+ add columns (ratio, uploaded)
+ add ratio to torrent info tab

### CODE REVIEW

**Comment by bill-ahmed** [comment]
Hey, thanks for opening up a PR! I've left a quick comment that should hopefully resolve a small issue. Let me know what you think.

**Comment by Biorn1950** [comment]
> Hey, thanks for opening up a PR! I've left a quick comment that should hopefully resolve a small issue. Let me know what you think.

Hi, I didn't find your comment.

**Review by bill-ahmed — CHANGES_REQUESTED** [review]

**Comment by bill-ahmed** [comment]
@Biorn1950 sorry about that, are you able to see it now?

**Comment by Biorn1950** [comment]
> @Biorn1950 sorry about that, are you able to see it now?

yep now I see it

**Review by bill-ahmed — APPROVED** [review]

**Comment by Biorn1950** [comment]
@bill-ahmed I've remove word-break hope that fix the issue.

**Comment by Biorn1950** [comment]
I make some test to change some design for my macbook 13" screen

Capture d’écran 2020-11-10 à 22 48 27

Do you know how to change size of button image properly ?

**Comment by bill-ahmed** [comment]
Are you referring to that person icon on the top-right? If so then yea i'm not too sure what's happening there, although I can take a look if you like. It should ideally be in a separate PR.

**Comment by bill-ahmed** [comment]
Going to do one last sanity check before merging this in :)

**Comment by Biorn1950** [comment]
ok, I'll going to check on the net how change the size of button-image with angular material. Or I'll use mat-mini-fab.

TY

**Comment by Biorn1950** [comment]
Capture d’écran 2020-11-11 à 00 50 28
Yes with mat-mini-fab it's easier.

**Pull request merged**
